### PR TITLE
Add the V2VAM fusion module

### PR DESCRIPTION
**Pull request by jinlong17**
form paper "Learning for Vehicle-to-Vehicle Cooperative Perception under Lossy Communication"

### CODE REVIEW

**Review by DerrickXuNu — CHANGES_REQUESTED** [review]
Hi Jinlong, thank for making contribution to Opencood. Please add these to the PR:
1. Please update the readme to indicate your method like others such as V2X-ViT
2. Please provide the performance metric on OPV2V benchmark table in readme file, and provide the pretrained model download link

**Comment by DerrickXuNu** [comment]
@jinlong17

**Comment by jinlong17** [comment]
copy that, I updated the readme file.

**Comment by jinlong17** [comment]
@DerrickXuNu

**Comment by DerrickXuNu** [comment]
The number looks incorrect to me. Why is the performance under compression higher than the ones without compression?

**Comment by jinlong17** [comment]
Hi Runsheng, I update the information and models.

**Review by DerrickXuNu — APPROVED** [review]

**Comment by DerrickXuNu** [comment]
LGTM, nice work!

**Pull request merged**
